#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Madagascar (Script do Madagascar)
#
# IMPORTANTE: Foi retirada a condição de borda absorvente do programa 'sfTestfd2d'
# para ilustrar os efeitos de borda na metodologia de diferenças finitas.
#
# Objetivo: Realizar a modelagem com DF de um modelo de uma fonte pontual em um meio
# de velocidade constante, de modo a exemplificar os efeitos da borda absorvente.
#
# Site: https://dirack.github.io
# 
# Versão 1.0
#
# Programador: Rodolfo A. C. Neves 10/05/2019
#
# email: rodolfo_profissional@hotmail.com

# Importe a Biblioteca do madagascar 
from rsf.proj import *

## Gerar o modelo de velocidades
Flow('vel',None,
        '''
        math output=2.0 n1=200 n2=200 d1=0.005 d2=0.005
        label1=x1 unit1=km label2=x2 unit2=km
        ''')

# Posição do receptor no grid
nr=25

receptor_com_borda='receiver_with_border'
receptor_sem_borda='receiver_no_border'

## Modelagem DF COM borda absorvente
Flow(['wav_com_borda',receptor_com_borda],'vel',
	'''
	./semborda.x border=y nb=30 nt=1000 dt=0.001 rec=${TARGETS[1]}
	''')
Plot('wav_com_borda','grey gainpanel=all title="Efeito COM borda" scalebar=y color=j scalebar=y',view=1)

Result(receptor_com_borda,
	'''
	wiggle title="Modelagem DF COM borda" transp=y poly=y yreverse=y
	''')

## Modelagem DF SEM borda absorvente
Flow(['wav_sem_borda',receptor_sem_borda],'vel',
	'''
	./semborda.x border=n nb=30 nt=1000 dt=0.001 rec=${TARGETS[1]}
	''')
Plot('wav_sem_borda','grey gainpanel=all title="Efeito SEM borda" scalebar=y color=j scalebar=y',view=1)

Result(receptor_sem_borda,
	'''
	wiggle title="Modelagem DF SEM borda" transp=y poly=y yreverse=y
	''')

End()


